performance_optimization:

# Performance Monitoring
monitoring:
  real_time_metrics: true
  performance_budgets: true
  automated_alerts: true

  kpis:
    app_launch_time: "target_1_5_seconds"
    screen_transition: "target_200ms"
    api_response_time: "target_300ms"
    database_query_time: "target_100ms"
    ui_frame_rate: "target_60fps"
    memory_usage: "target_80mb_max"

# Flutter Performance Optimization
flutter_performance:
  build_optimization:
    tree_shaking: true
    code_minification: true
    dead_code_elimination: true
    bundle_splitting: true

  widget_optimization:
    const_constructors: "enforced"
    repaint_boundaries: "auto_detection"
    widget_recycling: "aggressive"
    selective_rebuilds: "provider_selector"
    virtual_scrolling: "large_lists"

  memory_management:
    automatic_disposal: true
    image_cache_optimization: "50mb_limit"
    weak_references: "where_appropriate"
    garbage_collection_tuning: true

  animation_optimization:
    gpu_acceleration: true
    layer_caching: true
    physics_based_animations: true
    jank_detection: true

# Database Performance
database_performance:
  firestore_optimization:
    composite_indexes: "auto_generated"
    query_optimization: true
    connection_pooling: true

    query_patterns:
      pagination: "cursor_based_25_items"
      batch_operations: "preferred"
      transaction_optimization: true

  caching_strategy:
    level_1_device: "secure_storage_1hour_ttl"
    level_2_memory: "redis_24hour_ttl"
    level_3_cdn: "cloudflare_1week_ttl"

    cache_invalidation:
      strategy: "time_based_with_manual_override"
      dependency_tracking: true

# Network Performance
network_optimization:
  http_optimization:
    connection_pooling: true
    keep_alive_enabled: true
    request_compression: "gzip_brotli"
    response_compression: true

  request_optimization:
    batch_requests: "group_related_calls"
    request_deduplication: true
    retry_strategy: "exponential_backoff"
    timeout_optimization: "5s_connect_10s_read"

  offline_performance:
    cache_first_strategy: true
    background_sync: true
    critical_data_prefetch: true

# Asset Performance
asset_optimization:
  image_optimization:
    formats: ["webp", "avif", "jpg_fallback"]
    compression: "quality_85_progressive"
    responsive_variants: ["1x", "2x", "3x"]
    lazy_loading: "intersection_observer"

  bundle_optimization:
    code_splitting: "route_based"
    asset_bundling: "200kb_max_chunks"
    preloading_strategy: "critical_above_fold"

